kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: impersonator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: impersonator
subjects:
  - kind: ServiceAccount
    name: argo
