apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: multi-cluster
  labels:
    workflows.argoproj.io/test: "true"
spec:
  entrypoint: main
  templates:
    - name: main
      clusterName: other
      namespace: argo
      container:
        image: docker/whalesay:latest
